name = "xline"
version = "0.1.1"
homepage = "https://xline.cloud"
description = "A High-Performance Geo-distributed Metadata Management System"
repository = "https://github.com/xline-kv/Xline"
documentation = "https://datenlord.github.io/xline-home/#/docs/Get-Started"
license = "Apache-2.0"

keywords = ["distributed-systems", "cloud-native", "metadata", "geo", "key-value"]
categories = ["configuration-management", "distributed-configuration"]

[deploy]
image = "ghcr.io/xline-kv/xline:v0.6.1"
