name = ".envoy"
version = "0.1.0"
homepage = "https://www.envoyproxy.io/"
description = "Cloud-native high-performance edge/middle/service proxy"
repository = "https://github.com/envoyproxy/envoy"
documentation = "https://www.envoyproxy.io/docs"
license = "Apache-2.0"

keywords = ["HTTP", "proxy-server", "web-server", "middleware", "caching", "load-balancer", "reverse-proxy", "edge"]
categories = ["networking", "web-servers", "proxy-servers"]

[deploy]
image = "envoyproxy/envoy:v1.12.7"
