name = "haproxy"
version = "0.1.0"
homepage = "https://www.haproxy.org/"
description = "HAProxy - The Reliable, High Performance TCP/HTTP Load Balancer"
repository = "https://github.com/haproxy/haproxy/"
documentation = "http://docs.haproxy.org"
license = "GPL-2.0-or-later"

keywords = ["HTTP", "proxy-server", "web-server", "middleware", "caching", "load-balancer", "reverse-proxy"]
categories = ["networking", "web-servers", "proxy-servers"]

[deploy]
image = "haproxy:3.0"
